### ISSUE TITLE
Full case files

### ISSUE THREAD

**Issue by xadacka** [AlphamaxMedia/netv2-case#1]
Hey,

The front bezel files are perfect, they open and print great and are easy to edit. However, I'm wondering is it possible to get the main case files? I see "netv2-dvt-mechanical.zip" but when downloaded and extracted it gives me a 36.1MB file called "netv2-dvt-mechanical.STEP 2" that doesn't seem to open in anything, even when the " 2" is removed from the end. I'm not sure if it's a bad zip or if I'm trying to open it wrong but any help would be appreciated.

**Comment by bunnie** [comment]
I've committed a new STEP file, can you try it out? Hopefully it works.

**Comment by xadacka** [comment]
Same issue, can't seem to open the file and if I try to convert it to something else like an stl it shows one flat object so I'm not sure what's going on

**Comment by bunnie** [comment]
Hmmm....it is a hella complex STEP file, Solidworks struggles to open it.

I've added an STL version to the repo, can you open that?

**Comment by bunnie** [comment]
https://github.com/AlphamaxMedia/netv2-case/blob/master/netv2_asm_stl.zip

**Comment by xadacka** [comment]
That opened instantly, thank you!
